version: '3.3'
services:
  mysql:
    build: ./environments/development/docker/mysql
    ports:
      - "33067:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  phpfpm:
    build: ./environments/development/docker/php
    links:
     - mysql
    expose:
      - "9000"
    volumes:
     - ./environments/development/docker/php/php.ini:/usr/local/etc/php/php.ini
     - ./:/var/www/html
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 120s
    command: php-fpm

  nginx:
    build: ./environments/development/docker/nginx
    links:
      - phpfpm:phpfpm
    expose:
      - "80"
    volumes:
      - ./environments/development/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    environment:
      VIRTUAL_HOST: wordpress.local
    networks:
      default:
        aliases:
          - wordpress.local

  mailcatcher:
      image: schickling/mailcatcher
      ports:
       - "1080:1080"

networks:
  default:
    external:
      name: wordpress
